services:
  api:
    container_name: secure_otp-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - APP_NAME=${APP_NAME}
      - OTP_EXP_TIME=${OTP_EXP_TIME}
      - OTP_COUNTER_INIT=${OTP_COUNTER_INIT}
      - OTP_COUNTER_INCREMENT=${OTP_COUNTER_INCREMENT}
      - OTP_MAX_ATTEMPTS=${OTP_MAX_ATTEMPTS}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_AUTH_USER=${EMAIL_AUTH_USER}
      - EMAIL_AUTH_PASSWORD=${EMAIL_AUTH_PASSWORD}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
  redis:
    container_name: secure_otp-redis
    restart: always
    ports:
      - ${REDIS_EXPOSE_PORT:-6379}:6379
    volumes:
      - ./DATA/REDIS_DATA:/data
    environment:
      - REDIS_ARGS=--appendonly yes