version: '3.8'

services:
  api:
    container_name: secure_otp-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
  redis:
    container_name: secure_otp-redis
    restart: always
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    volumes:
      - /DATA/REDIS_DATA:/data
